"""
models.py -- Pydantic models for the Brasaland Supplier Directory API.

These classes define what a "supplier" looks like, and Pydantic
automatically checks that any data coming into the API follows the
rules from CONTEXT-brasaland.md:
  - country must be "Colombia" or "USA"
  - currency must match the country (Colombia -> COP, USA -> USD)
  - categories must be a non-empty list of valid categories
  - rate_per_unit must be greater than 0
  - status must be "active" or "suspended"

If any of these rules are broken, FastAPI will send back a 422 error
on its own -- we don't have to write that error-handling by hand.
"""

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field, model_validator


# ---------------------------------------------------------------------------
# Enums restrict a field to a fixed set of allowed values. If a client
# sends anything outside of these options, Pydantic rejects it before
# it ever reaches our code.
# ---------------------------------------------------------------------------

class Country(str, Enum):
    COLOMBIA = "Colombia"
    USA = "USA"


class Currency(str, Enum):
    COP = "COP"
    USD = "USD"


class SupplierStatus(str, Enum):
    ACTIVE = "active"
    SUSPENDED = "suspended"


class Category(str, Enum):
    CARNE = "carne"
    VERDURAS_Y_HORTALIZAS = "verduras_y_hortalizas"
    SALSAS_Y_CONDIMENTOS = "salsas_y_condimentos"
    BEBIDAS = "bebidas"
    PACKAGING = "packaging"
    PRODUCTOS_LIMPIEZA = "productos_limpieza"
    LACTEOS = "lacteos"
    CARBON_Y_COMBUSTIBLE = "carbon_y_combustible"


# A small lookup table so we can check "does this currency match this
# country?" with one dictionary read instead of an if/else chain.
COUNTRY_CURRENCY_MAP = {
    Country.COLOMBIA: Currency.COP,
    Country.USA: Currency.USD,
}


# ---------------------------------------------------------------------------
# SupplierBase holds every field that both incoming (create) and outgoing
# (response) suppliers share. We put shared fields and the shared
# validator here once, then build the other two models on top of it,
# instead of repeating the same fields twice.
# ---------------------------------------------------------------------------

class SupplierBase(BaseModel):
    name: str = Field(..., min_length=1, description="Supplier trade name")
    country: Country
    categories: list[Category] = Field(..., min_length=1)
    rate_per_unit: float = Field(..., gt=0, description="Rate per unit, must be positive")
    currency: Currency
    status: SupplierStatus = SupplierStatus.ACTIVE
    contact_email: Optional[str] = None
    notes: Optional[str] = None

    # mode="after" means this runs once all the individual fields above
    # have already passed their own checks -- so by the time this runs,
    # we know self.country and self.currency both exist and are valid.
    @model_validator(mode="after")
    def check_currency_matches_country(self):
        expected_currency = COUNTRY_CURRENCY_MAP[self.country]
        if self.currency != expected_currency:
            raise ValueError(
                f"Currency must be {expected_currency.value} for suppliers in "
                f"{self.country.value}, got {self.currency.value}"
            )
        return self


# ---------------------------------------------------------------------------
# SupplierCreate -- what the client sends in the body of POST /suppliers.
# It's just SupplierBase with nothing added: no id, no updated_at, because
# those are generated by the server, not sent by the client.
# ---------------------------------------------------------------------------

class SupplierCreate(SupplierBase):
    pass


# ---------------------------------------------------------------------------
# Supplier -- what the API sends back to the client. Same fields as
# SupplierBase, plus the two system-generated fields.
# ---------------------------------------------------------------------------

class Supplier(SupplierBase):
    id: int
    updated_at: datetime


# ---------------------------------------------------------------------------
# Small, single-purpose models for the two PATCH endpoints. Each one only
# accepts the one field it's allowed to change, so a request can't sneak
# in an update to, say, the name while "just updating the rate."
# ---------------------------------------------------------------------------

class SupplierRateUpdate(BaseModel):
    rate_per_unit: float = Field(..., gt=0)


class SupplierStatusUpdate(BaseModel):
    status: SupplierStatus